name: Webhook Trigger

on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, closed]  # 'closed' helps capture merges if PR is merged

jobs:
  trigger_webhook:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Trigger Webhook
        run: |
          echo "Sending webhook..."
          curl -X POST https://9f5373793444.ngrok-free.app/webhook \
          -H "Content-Type: application/json" \
          -d '{
            "request_id": "'${{ github.sha }}'",
            "author": "'${{ github.actor }}'",
            "action": "'${{ github.event_name }}'",
            "from_branch": "'${{ github.head_ref || github.ref_name }}'",
            "to_branch": "'${{ github.base_ref || github.ref_name }}'",
            "timestamp": "'$(date -u +"%Y-%m-%dT%H:%M:%SZ")'"
          }'
